# Generated by Django 4.0.3 on 2022-10-13 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prealert', '0019_remove_storeentrance_transaction_type_and_more'),
        ('customer', '0002_remove_packaging_packaging_capacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='ware_house',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ware_house_customer', to='prealert.warehouse'),
        ),
        migrations.AddField(
            model_name='product',
            name='management_type',
            field=models.CharField(choices=[('Mass', 'Mass'), ('Lot', 'Lot')], default='Mass', max_length=100, verbose_name='Type'),
        ),
    ]
