# Generated by Django 4.0.3 on 2022-10-14 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_transport_product_ware_house'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transport',
            options={'verbose_name': 'Transporter', 'verbose_name_plural': 'Transporters'},
        ),
    ]
