# Generated by Django 4.0.3 on 2022-10-26 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prealert', '0025_alter_storeoutlet_options'),
        ('customer', '0005_alter_transport_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='ware_house',
        ),
        migrations.AddField(
            model_name='customer',
            name='ware_house',
            field=models.ManyToManyField(null=True, related_name='ware_house_customer', to='prealert.warehouse'),
        ),
    ]
