# Generated by Django 4.0.3 on 2022-10-28 05:03

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


def set_package_type(apps, schema_editor):
    Packaging = apps.get_model('customer', 'Packaging')
    Packaging.objects.delete()
    PackagingType = apps.get_model('customer', 'PackagingType')
    packaging_type = PackagingType.objects.create(package_type="Bags")

    for row in Packaging.objects.all():
        row.packaging_type = packaging_type
        row.save()


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_remove_customer_ware_house_customer_ware_house'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackagingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('package_type', models.CharField(blank=True, max_length=400, null=True, verbose_name='Package Type')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='packaging',
            name='packaging_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packaging_type_pack', to='customer.packagingtype'),
        ),
        migrations.RunPython(set_package_type,
                             reverse_code=migrations.RunPython.noop),
    ]
