# Generated by Django 4.0.3 on 2022-10-26 08:04

from django.db import migrations


def set_package_type(apps, schema_editor):
    MyModel = apps.get_model('customer', 'Packaging')
    PackagingType = apps.get_model('customer', 'PackagingType')
    packaging_type = PackagingType.objects.create(name="Bags")

    for row in MyModel.objects.all():
        if isinstance(row.packaging_type, str):
            row.packaging_type = packaging_type
            row.save()


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_remove_customer_ware_house_customer_ware_house'),
    ]

    operations = [
        migrations.RunPython(set_package_type,
                             reverse_code=migrations.RunPython.noop),
    ]
