# Generated by Django 4.0.3 on 2022-10-09 22:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Entity')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GuaranteedGoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('batch_number', models.CharField(blank=True, max_length=400, null=True, verbose_name='Batch Number ')),
                ('quantity', models.IntegerField(blank=True, null=True, verbose_name='Quantity')),
                ('quantity_pledged', models.IntegerField(blank=True, null=True, verbose_name='Quantity Pledged')),
                ('theoretical_weight', models.IntegerField(blank=True, null=True, verbose_name='Theoretical Weight')),
                ('theoretical_weight_pledged', models.IntegerField(blank=True, null=True, verbose_name='Theoretical Weight Pledged')),
                ('actual_weight', models.IntegerField(blank=True, null=True, verbose_name='Actual Weight')),
                ('actual_weight_guaranteed', models.IntegerField(blank=True, null=True, verbose_name='Actual Weight Guaranteed')),
                ('priority', models.CharField(choices=[('Incoming', 'Incoming'), ('Outgoing', 'Outgoing'), ('Finished', 'Finished')], default='Incoming', max_length=100, verbose_name='Priority')),
            ],
            options={
                'verbose_name': 'Holding certificate',
                'verbose_name_plural': 'Holding certificate',
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(blank=True, max_length=400, null=True, verbose_name='Season')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WareHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(blank=True, max_length=400, null=True, verbose_name='Ware House Name ')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WeighBridge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('vehicle_number', models.CharField(blank=True, max_length=400, null=True, verbose_name='Vehicle Number')),
                ('transporter', models.CharField(blank=True, max_length=400, null=True, verbose_name='Transporter')),
                ('vehicle_reg_num', models.CharField(blank=True, max_length=400, null=True, verbose_name='Vehicle Registration Number')),
                ('account_id', models.CharField(blank=True, max_length=400, null=True, verbose_name='Account ID')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='Exit Time')),
                ('trailer_reg_num', models.CharField(blank=True, max_length=400, null=True, verbose_name='Trailer Registration Number')),
                ('entry_date', models.DateField(blank=True, null=True, verbose_name='Entry Date')),
                ('exit_time', models.TimeField(blank=True, null=True, verbose_name='Exit Time')),
                ('print_date', models.DateField(blank=True, null=True, verbose_name='Print Date')),
                ('_import', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=400, verbose_name='Inbound')),
                ('_export', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=400, verbose_name='Outbound')),
                ('from_destination', django_countries.fields.CountryField(blank=True, default='FR', max_length=300)),
                ('to_destination', django_countries.fields.CountryField(blank=True, default='FR', max_length=300)),
                ('first_weight', models.FloatField(blank=True, max_length=400, null=True, verbose_name='First Weight')),
                ('second_weight', models.FloatField(blank=True, max_length=400, null=True, verbose_name='Second Weight')),
                ('net_weight', models.FloatField(blank=True, max_length=400, null=True, verbose_name='Net Weight')),
                ('client_name_field', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_name_weight', to=settings.AUTH_USER_MODEL)),
                ('commodity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commodity_weigh_bridge', to='customer.product')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_name_weigh_bridge', to='customer.customer')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weighbridge', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StoreEntrance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('client_name', models.CharField(blank=True, max_length=400, null=True, verbose_name='Client Name')),
                ('flux', models.CharField(choices=[('Import', 'Import'), ('Export', 'Export')], default='Incoming', max_length=100, verbose_name='Flux')),
                ('store', models.CharField(blank=True, max_length=400, null=True, verbose_name='Store')),
                ('country_of_origin', django_countries.fields.CountryField(max_length=2)),
                ('po_number', models.CharField(blank=True, max_length=400, null=True, verbose_name='PO NUmber')),
                ('shipment_number', models.CharField(blank=True, max_length=400, null=True, verbose_name='Ship Number')),
                ('number_of_batch', models.IntegerField(blank=True, null=True, verbose_name='Number of batch')),
                ('entry_date', models.DateField(blank=True, null=True, verbose_name='Entry Date')),
                ('quantity', models.FloatField(blank=True, null=True, verbose_name='Quantity')),
                ('client_reference', models.CharField(blank=True, max_length=400, null=True, verbose_name='Client Reference')),
                ('contract_number', models.CharField(blank=True, max_length=400, null=True, verbose_name='Contract Number')),
                ('client_name_field', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_name_store', to=settings.AUTH_USER_MODEL)),
                ('packaging', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packaging_store_entrance', to='customer.packaging')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_store_entrance', to='customer.product')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_entrance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Store Entrance',
                'verbose_name_plural': 'Store Entrance',
            },
        ),
        migrations.CreateModel(
            name='ProductStoreEntrance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('purchase_order_number', models.CharField(blank=True, max_length=400, null=True, verbose_name='Purchase order number')),
                ('shipment_number', models.CharField(blank=True, max_length=400, null=True, verbose_name='Shipment  number')),
                ('batch_number', models.CharField(blank=True, max_length=400, null=True, verbose_name='Batch  number')),
                ('compliance', models.CharField(blank=True, max_length=400, null=True, verbose_name='Compliance')),
                ('amount', models.FloatField(blank=True, max_length=400, null=True, verbose_name='Amount')),
                ('grade', models.CharField(blank=True, max_length=400, null=True, verbose_name='Grade')),
                ('mark', models.CharField(blank=True, max_length=400, null=True, verbose_name='Mark')),
                ('theoretical_weight', models.IntegerField(blank=True, null=True, verbose_name='Theoretical Weight')),
                ('actual_weight', models.IntegerField(blank=True, null=True, verbose_name='Actual Weight')),
                ('zone_warehouse', models.FloatField(blank=True, max_length=400, null=True, verbose_name='Zone warehouse')),
                ('product_comments', models.CharField(blank=True, max_length=400, null=True, verbose_name='Product Comments')),
                ('packaging', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packaging_store_entrance_product', to='customer.packaging')),
                ('store_entrance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_entrance_entrance', to='prealert.storeentrance')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PreAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('quantity', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Quantity')),
                ('contract_number', models.CharField(blank=True, max_length=400, null=True, verbose_name='Contract Number')),
                ('from_or_origin', django_countries.fields.CountryField(max_length=2)),
                ('commentaries', models.TextField(blank=True, null=True, verbose_name='Commentaries')),
                ('type', models.CharField(choices=[('Inbound', 'Inbound'), ('Outbound', 'Outbound')], default='Inbound', max_length=100, verbose_name='Type')),
                ('notifications', models.BooleanField(default=False, verbose_name='Notifications')),
                ('status', models.CharField(choices=[('Incoming', 'Incoming'), ('Outgoing', 'Outgoing'), ('Finished', 'Finished')], default='Incoming', max_length=100, verbose_name='Status')),
                ('priority', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='High', max_length=100, verbose_name='Priority')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_name_pre_alert', to='customer.customer')),
                ('packaging', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packaging_pre_alert', to='customer.packaging')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_pre_alert', to='customer.product')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prealert', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='ManagementByLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('transaction_type', models.CharField(choices=[('Inbound', 'Inbound'), ('Outbound', 'Outbound')], default='Inbound', max_length=100, verbose_name='Transaction Type')),
                ('batch_number', models.CharField(blank=True, max_length=400, null=True, verbose_name='Batch Number ')),
                ('quantity', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Quantity')),
                ('real_weight', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Real weight ')),
                ('quantity_hc', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Quantity HC')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_lot', to='customer.customer')),
                ('packaging', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packaging_lot', to='customer.packaging')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_lot', to='customer.product')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HousingCertificateSearchModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_hcm', to='customer.customer')),
                ('entity', models.ManyToManyField(to='prealert.entity')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_hcm', to='customer.product')),
                ('season', models.ManyToManyField(to='prealert.season')),
                ('ware', models.ManyToManyField(to='prealert.warehouse')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CarrierStoreEntrance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('carrier_identifier', models.CharField(blank=True, max_length=400, null=True, verbose_name='Carrier Identifier')),
                ('container_number', models.CharField(blank=True, max_length=400, null=True, verbose_name='Container Number')),
                ('registration_number', models.CharField(blank=True, max_length=400, null=True, verbose_name='Registration Number')),
                ('carrier_type', models.CharField(blank=True, max_length=400, null=True, verbose_name='Carrier Type')),
                ('entry_slip_number', models.CharField(blank=True, max_length=400, null=True, verbose_name='Entry slip Number')),
                ('licence_number', models.CharField(blank=True, max_length=400, null=True, verbose_name='Licence Number')),
                ('trailer_number', models.CharField(blank=True, max_length=400, null=True, verbose_name='Trailer Number')),
                ('supervisor_name', models.CharField(blank=True, max_length=400, null=True, verbose_name='Supervisor Name')),
                ('product_entry_date', models.DateField(blank=True, null=True, verbose_name='Product Entry Date')),
                ('guardian_name', models.CharField(blank=True, max_length=400, null=True, verbose_name='Guardian Name')),
                ('comments', models.TextField(blank=True, max_length=400, null=True, verbose_name='Comments')),
                ('store_entrance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_entrance_carrier', to='prealert.storeentrance')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
