# Generated by Django 4.0.3 on 2022-08-16 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prealert', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weighbridge',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weighbridge', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='storeentrance',
            name='packaging',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packaging_store_entrance', to='customer.packaging'),
        ),
        migrations.AddField(
            model_name='storeentrance',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_store_entrance', to='customer.product'),
        ),
        migrations.AddField(
            model_name='storeentrance',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_entrance', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prealert',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_name_pre_alert', to='customer.customer'),
        ),
        migrations.AddField(
            model_name='prealert',
            name='packaging',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packaging_pre_alert', to='customer.packaging'),
        ),
        migrations.AddField(
            model_name='prealert',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_pre_alert', to='customer.product'),
        ),
        migrations.AddField(
            model_name='prealert',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prealert', to=settings.AUTH_USER_MODEL),
        ),
    ]
