# Generated by Django 4.0.3 on 2022-07-15 17:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prealert', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guaranteedgoods',
            options={'get_latest_by': 'modified'},
        ),
        migrations.AddField(
            model_name='guaranteedgoods',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guaranteedgoods',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.CreateModel(
            name='StoreEntrance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('transaction_type', models.CharField(blank=True, max_length=400, null=True, verbose_name='Transaction Type')),
                ('product', models.IntegerField(blank=True, null=True, verbose_name='Product')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('client_name', models.CharField(blank=True, max_length=400, null=True, verbose_name='Client Name')),
                ('flux', models.CharField(choices=[('Import', 'Import'), ('Export', 'Export')], default='Incoming', max_length=100, verbose_name='Flux')),
                ('store', models.CharField(blank=True, max_length=400, null=True, verbose_name='Store')),
                ('po_number', models.CharField(blank=True, max_length=400, null=True, verbose_name='PO NUmber')),
                ('shipment_number', models.CharField(blank=True, max_length=400, null=True, verbose_name='Ship Number')),
                ('amount', models.FloatField(blank=True, null=True, verbose_name='Amount')),
                ('packaging', models.IntegerField(blank=True, null=True, verbose_name='Packaging')),
                ('theoretical_weight', models.IntegerField(blank=True, null=True, verbose_name='Theoretical Weight')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_entrance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
