# Generated by Django 4.0.3 on 2022-08-07 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        ('prealert', '0003_remove_prealert_customer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prealert',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_name_pre_alert', to='customer.customer'),
        ),
        migrations.AddField(
            model_name='prealert',
            name='packaging',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packaging_pre_alert', to='customer.packaging'),
        ),
        migrations.AddField(
            model_name='storeentrance',
            name='packaging',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packaging_store_entrance', to='customer.packaging'),
        ),
        migrations.AddField(
            model_name='weighbridge',
            name='commodity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commodity_weigh_bridge', to='customer.product'),
        ),
    ]
