# Generated by Django 4.0.3 on 2022-09-06 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prealert', '0003_prealert_commentaries_prealert_contract_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prealert',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='weighbridge',
            name='_export',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Export'),
        ),
        migrations.AddField(
            model_name='weighbridge',
            name='_import',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Import'),
        ),
        migrations.AddField(
            model_name='weighbridge',
            name='account_id',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Account ID'),
        ),
        migrations.AddField(
            model_name='weighbridge',
            name='client_name',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Client Name'),
        ),
        migrations.AddField(
            model_name='weighbridge',
            name='first_weight',
            field=models.FloatField(blank=True, max_length=400, null=True, verbose_name='First Weight'),
        ),
        migrations.AddField(
            model_name='weighbridge',
            name='from_destination',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='From'),
        ),
        migrations.AddField(
            model_name='weighbridge',
            name='net_weight',
            field=models.FloatField(blank=True, max_length=400, null=True, verbose_name='Net Weight'),
        ),
        migrations.AddField(
            model_name='weighbridge',
            name='second_name',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Second Name'),
        ),
        migrations.AddField(
            model_name='weighbridge',
            name='time',
            field=models.TimeField(blank=True, null=True, verbose_name='Exit Time'),
        ),
        migrations.AddField(
            model_name='weighbridge',
            name='to_destination',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='To'),
        ),
    ]
