# Generated by Django 4.0.3 on 2022-09-23 17:46

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_remove_packaging_packaging_capacity_and_more'),
        ('prealert', '0005_storeentrance_client_reference_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarrierStoreEntrance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('carrier_identifier', models.CharField(blank=True, max_length=400, null=True, verbose_name='Carrier Identifier')),
                ('container_number', models.CharField(blank=True, max_length=400, null=True, verbose_name='Container Number')),
                ('registration_number', models.CharField(blank=True, max_length=400, null=True, verbose_name='Registration Number')),
                ('carrier_type', models.CharField(blank=True, max_length=400, null=True, verbose_name='Carrier Type')),
                ('entry_slip_number', models.CharField(blank=True, max_length=400, null=True, verbose_name='Entry slip Number')),
                ('licence_number', models.CharField(blank=True, max_length=400, null=True, verbose_name='Licence Number')),
                ('trailer_number', models.CharField(blank=True, max_length=400, null=True, verbose_name='Trailer Number')),
                ('supervisor_name', models.CharField(blank=True, max_length=400, null=True, verbose_name='Supervisor Name')),
                ('product_entry_date', models.DateField(blank=True, null=True, verbose_name='Product Entry Date')),
                ('guardian_name', models.CharField(blank=True, max_length=400, null=True, verbose_name='Guardian Name')),
                ('comments', models.TextField(blank=True, max_length=400, null=True, verbose_name='Comments')),
                ('store_entrance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_entrance_carrier', to='prealert.storeentrance')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductStoreEntrance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('purchase_order_number', models.CharField(blank=True, max_length=400, null=True, verbose_name='Purchase order number')),
                ('shipment_number', models.CharField(blank=True, max_length=400, null=True, verbose_name='Shipment  number')),
                ('batch_number', models.CharField(blank=True, max_length=400, null=True, verbose_name='Batch  number')),
                ('compliance', models.CharField(blank=True, max_length=400, null=True, verbose_name='Compliance')),
                ('amount', models.FloatField(blank=True, max_length=400, null=True, verbose_name='Amount')),
                ('grade', models.CharField(blank=True, max_length=400, null=True, verbose_name='Grade')),
                ('mark', models.CharField(blank=True, max_length=400, null=True, verbose_name='Mark')),
                ('theoretical_weight', models.IntegerField(blank=True, null=True, verbose_name='Theoretical Weight')),
                ('actual_weight', models.IntegerField(blank=True, null=True, verbose_name='Actual Weight')),
                ('zone_warehouse', models.FloatField(blank=True, max_length=400, null=True, verbose_name='Zone warehouse')),
                ('product_comments', models.CharField(blank=True, max_length=400, null=True, verbose_name='Product Comments')),
                ('carrier_store_entrance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_entrance_product', to='prealert.carrierstoreentrance')),
                ('packaging', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packaging_store_entrance_product', to='customer.packaging')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
