# Generated by Django 4.0.3 on 2022-09-28 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prealert', '0007_remove_productstoreentrance_carrier_store_entrance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prealert',
            name='quantity',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Quantity'),
        ),
    ]
