# Generated by Django 4.0.3 on 2022-09-28 20:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prealert', '0008_alter_prealert_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeentrance',
            name='client_name_field',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_name_store', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='weighbridge',
            name='client_name_field',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_name_weight', to=settings.AUTH_USER_MODEL),
        ),
    ]
