# Generated by Django 4.0.3 on 2022-09-28 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prealert', '0009_alter_storeentrance_client_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storeentrance',
            old_name='client_name',
            new_name='client_name_field',
        ),
        migrations.RenameField(
            model_name='weighbridge',
            old_name='client_name',
            new_name='client_name_field',
        ),
    ]
