# Generated by Django 4.0.3 on 2022-09-28 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prealert', '0009_storeentrance_client_name_field_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guaranteedgoods',
            options={'verbose_name': 'Holding certificate', 'verbose_name_plural': 'Holding certificate'},
        ),
        migrations.AlterModelOptions(
            name='storeentrance',
            options={'verbose_name': 'Store Entrance', 'verbose_name_plural': 'Store Entrance'},
        ),
        migrations.RemoveField(
            model_name='prealert',
            name='weight',
        ),
    ]
