# Generated by Django 4.0.3 on 2022-09-28 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prealert', '0010_alter_guaranteedgoods_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weighbridge',
            name='client_name',
        ),
    ]
