# Generated by Django 4.0.3 on 2022-09-30 23:43

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_remove_packaging_packaging_capacity_and_more'),
        ('prealert', '0011_remove_weighbridge_client_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='HousingCertificateSearchModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('ware', models.CharField(blank=True, max_length=400, null=True, verbose_name='Ware house')),
                ('season', models.CharField(blank=True, max_length=400, null=True, verbose_name='Season')),
                ('entity', models.FloatField(blank=True, max_length=400, null=True, verbose_name='Entity')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_hcm', to='customer.customer')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_hcm', to='customer.product')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
