# Generated by Django 4.0.3 on 2022-10-01 04:54

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_remove_packaging_packaging_capacity_and_more'),
        ('prealert', '0013_alter_housingcertificatesearchmodel_entity'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagementByLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('transaction_type', models.CharField(choices=[('Inbound', 'Inbound'), ('Outbound', 'Outbound')], default='Inbound', max_length=100, verbose_name='Transaction Type')),
                ('batch_number', models.CharField(blank=True, max_length=400, null=True, verbose_name='Batch Number ')),
                ('quantity', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Quantity')),
                ('real_weight', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Real weight ')),
                ('quantity_hc', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Quantity HC')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_lot', to='customer.customer')),
                ('packaging', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packaging_lot', to='customer.packaging')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_lot', to='customer.product')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
