# Generated by Django 4.0.3 on 2022-10-04 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prealert', '0013_alter_housingcertificatesearchmodel_entity'),
    ]

    def gen_field(apps, schema_editor):
        MyModel = apps.get_model('prealert', 'WeighBridge')
        for row in MyModel.objects.all():
            row._import = 'Yes'
            row._export = 'Yes'
            row.save()

    operations = [
        migrations.RunPython(gen_field, reverse_code=migrations.RunPython.noop),
    ]
