# Generated by Django 4.0.3 on 2022-10-03 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prealert', '0015_entity_season_warehouse_remove_weighbridge_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weighbridge',
            name='_export',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=400, verbose_name='Outbound'),
        ),
        migrations.AlterField(
            model_name='weighbridge',
            name='_import',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=400, verbose_name='Inbound'),
        ),
    ]
