# Generated by Django 4.0.3 on 2022-10-04 17:52

from django.db import migrations


class Migration(migrations.Migration):

    def gen_field(apps, schema_editor):
        MyModel = apps.get_model('prealert', 'WeighBridge')
        for row in MyModel.objects.all():
            row.second_name = 0
            row.save()


    dependencies = [
        ('prealert', '0015_auto_20221004_1745'),
    ]

    operations = [
        migrations.RunPython(gen_field, reverse_code=migrations.RunPython.noop),
    ]
