# Generated by Django 4.0.3 on 2022-10-04 17:54

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_remove_packaging_packaging_capacity_and_more'),
        ('prealert', '0016_auto_20221004_1752'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Entity')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(blank=True, max_length=400, null=True, verbose_name='Season')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WareHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(blank=True, max_length=400, null=True, verbose_name='Ware House Name ')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='weighbridge',
            name='second_name',
        ),
        migrations.RemoveField(
            model_name='weighbridge',
            name='status',
        ),
        migrations.AddField(
            model_name='weighbridge',
            name='second_weight',
            field=models.FloatField(blank=True, max_length=400, null=True, verbose_name='Second Weight'),
        ),
        migrations.RemoveField(
            model_name='housingcertificatesearchmodel',
            name='entity',
        ),
        migrations.RemoveField(
            model_name='housingcertificatesearchmodel',
            name='season',
        ),
        migrations.RemoveField(
            model_name='housingcertificatesearchmodel',
            name='ware',
        ),
        migrations.AlterField(
            model_name='weighbridge',
            name='_export',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=400, verbose_name='Outbound'),
        ),
        migrations.AlterField(
            model_name='weighbridge',
            name='_import',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=400, verbose_name='Inbound'),
        ),
        migrations.AlterField(
            model_name='weighbridge',
            name='from_destination',
            field=django_countries.fields.CountryField(blank=True, default='FR', max_length=300),
        ),
        migrations.AlterField(
            model_name='weighbridge',
            name='to_destination',
            field=django_countries.fields.CountryField(blank=True, default='FR', max_length=300),
        ),
        migrations.CreateModel(
            name='ManagementByLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('transaction_type', models.CharField(choices=[('Inbound', 'Inbound'), ('Outbound', 'Outbound')], default='Inbound', max_length=100, verbose_name='Transaction Type')),
                ('batch_number', models.CharField(blank=True, max_length=400, null=True, verbose_name='Batch Number ')),
                ('quantity', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Quantity')),
                ('real_weight', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Real weight ')),
                ('quantity_hc', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Quantity HC')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_lot', to='customer.customer')),
                ('packaging', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packaging_lot', to='customer.packaging')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_lot', to='customer.product')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='housingcertificatesearchmodel',
            name='entity',
            field=models.ManyToManyField(to='prealert.entity'),
        ),
        migrations.AddField(
            model_name='housingcertificatesearchmodel',
            name='season',
            field=models.ManyToManyField(to='prealert.season'),
        ),
        migrations.AddField(
            model_name='housingcertificatesearchmodel',
            name='ware',
            field=models.ManyToManyField(to='prealert.warehouse'),
        ),
    ]
