# Generated by Django 4.0.3 on 2022-10-03 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prealert', '0016_alter_weighbridge__export_alter_weighbridge__import'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weighbridge',
            name='second_name',
            field=models.FloatField(blank=True, max_length=400, null=True, verbose_name='Second Weight'),
        ),
    ]
