# Generated by Django 4.0.3 on 2022-10-03 12:38

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('prealert', '0017_alter_weighbridge_second_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weighbridge',
            name='from_destination',
            field=django_countries.fields.CountryField(default='UG', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='weighbridge',
            name='to_destination',
            field=django_countries.fields.CountryField(default='UG', max_length=2),
            preserve_default=False,
        ),
    ]
