# Generated by Django 4.0.3 on 2022-10-04 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_remove_packaging_packaging_capacity_and_more'),
        ('prealert', '0017_entity_season_warehouse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weighbridge',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_name_weigh_bridge', to='customer.customer'),
        ),
    ]
