# Generated by Django 4.0.3 on 2022-10-05 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prealert', '0018_weighbridge_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeentrance',
            name='transaction_type',
        ),
        migrations.RemoveField(
            model_name='storeentrance',
            name='type_of_management',
        ),
    ]
