# Generated by Django 4.0.3 on 2022-10-13 12:19

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_customer_ware_house_product_management_type'),
        ('prealert', '0019_remove_storeentrance_transaction_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaWareHouse',
            fields=[
                ('warehouse_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='prealert.warehouse')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
            bases=('prealert.warehouse',),
        ),
        migrations.AddField(
            model_name='weighbridge',
            name='management_type',
            field=models.CharField(choices=[('Kg', 'Kg'), ('Tonnes', 'Tonnes')], default='Kg', max_length=100, verbose_name='Measure Type'),
        ),
        migrations.CreateModel(
            name='Factories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_factories', to='customer.product')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
