# Generated by Django 4.0.3 on 2022-10-14 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prealert', '0022_alter_entity_options_alter_factories_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstoreentrance',
            name='carrier_store_entrance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carrier_store_entrance', to='prealert.carrierstoreentrance'),
        ),
    ]
