# Generated by Django 4.0.3 on 2022-10-25 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prealert', '0023_alter_productstoreentrance_carrier_store_entrance'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreOutlet',
            fields=[
                ('storeentrance_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='prealert.storeentrance')),
            ],
            options={
                'verbose_name': 'Store Entrance',
                'verbose_name_plural': 'Store Entrance',
            },
            bases=('prealert.storeentrance',),
        ),
    ]
