# Generated by Django 4.0.3 on 2022-10-25 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prealert', '0024_storeoutlet'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storeoutlet',
            options={'verbose_name': 'Store outlet', 'verbose_name_plural': 'Store outlet'},
        ),
    ]
